name: test

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Retrive PR infos
      run: |
        echo ${{ github.sha }}
        echo ${{ github.ref }}
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Trigger Api tests
      uses: wei/curl@v1.1.1
      with:
        args: -X POST "https://api.bitrise.io/v0.1/test/builds"
    
