name: test

on: 
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrive PR infos
      run: |
        echo the commit sha is ${{ github.sha }}
        echo the branch name is ${{ github.event.pull_request.head.ref }}
        echo the repo url is https://github.com/${{ github.repository }}
       
    - name: Trigger Api tests
      uses: wei/curl@v1.1.1
      with:
        args: -X POST "https://api.bitrise.io/v0.1/test/builds"
    
